name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Ejecutar Doxygen
        uses: mattnotmitt/doxygen-action@edge
        with:
          working-directory: ./docs

      - name: Añadir archivo .nojekyll
        run: touch ./docs/html/.nojekyll

      - name: Deploy a GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs/html
          force_orphan: true